spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/muralimreddy/shoppingapp/config
server:
  port: 8001

  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/